name: simple-agent-demo
region: nyc

services:
  - name: agent-api
    github:
      repo: YOUR_GITHUB_USERNAME/simple-agent-demo
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile

    http_port: 3000

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "3000"
        scope: RUN_TIME

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
